var rooms = [ 
		 { name: "JJ017",
		   building: "Ann Packer",
           park: "East",
           type: "Seminar",
		   capacity: 16,
		   dataProj: false,
		   ohp: true,
		   whiteboard: true,
		   chalkboard: true,
		   wheelchair: true } ,
		 { name: "K103",
		   building: "Herbert Manzoni",
           park: "Central",
           type: "Seminar",
		   capacity: 13,
		   dataProj: false,
		   ohp: false,
		   whiteboard: false,
		   chalkboard: false,
		   wheelchair: true } ,
		 { name: "S175",
		   building: "S Building",
           park: "West",
           type: "Seminar",
		   capacity: 10,
		   dataProj: false,
		   ohp: true,
		   whiteboard: true,
		   chalkboard: false,
		   wheelchair: true } ,
		 { name: "W05E",
		   building: "Sir David Davies",
           park: "West",
           type: "Seminar",
		   capacity: 10,
		   dataProj: false,
		   ohp: false,
		   whiteboard: true,
		   chalkboard: false,
		   wheelchair: true } ,
		 { name: "W05F",
		   building: "Sir David Davies",
           park: "West",
           type: "Seminar",
		   capacity: 8,
		   dataProj: false,
		   ohp: false,
		   whiteboard: true,
		   chalkboard: false,
		   wheelchair: true } ,
		 { name: "RT003",
		   building: "Sir Frank Gibb",
           park: "West",
           type: "Traditional",
		   capacity: 300,
		   dataProj: true,
		   ohp: false,
		   whiteboard: false,
		   chalkboard: false,
		   wheelchair: true} ,
		 { name: "CC011",
		   building: "James France",
           park: "Central",
           type: "Traditional",
		   capacity: 256,
		   dataProj: true,
		   ohp: true,
		   whiteboard: true,
		   chalkboard: false,
		   wheelchair: true} ,
		 { name: "Cope",
		   building: "Cope Auditorium",
           park: "East",
           type: "Traditional",
		   capacity: 226,
		   dataProj: true,
		   ohp: false,
		   whiteboard: false,
		   chalkboard: false,
		   wheelchair: true} ,
		 { name: "U020",
		   building: "Brockington Extension",
           park: "Central",
           type: "Traditional",
		   capacity: 218,
		   dataProj: true,
		   ohp: true,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true} , 
		   { name: "CC012",
		   building: "James France",
           park: "Central",
           type: "Traditional",
		   capacity: 218,
		   dataProj: true,
		   ohp: true,
		   whiteboard: true,
		   chalkboard: false,
		   wheelchair: true} ,
		   { name: "CC013",
		   building: "James France",
           park: "Central",
           type: "Traditional",
		   capacity: 176,
		   dataProj: true,
		   ohp: true,
		   whiteboard: true,
		   chalkboard: false,
		   wheelchair: true},
		   { name: "J104",
		   building: "EHB",
           park: "Central",
           type: "Traditional",
		   capacity: 153,
		   dataProj: true,
		   ohp: true,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "RT008",
		   building: "Sir Frank Gibb",
           park: "West",
           type: "Traditional",
		   capacity: 148,
		   dataProj: true,
		   ohp: false,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "W001",
		   building: "Sir David Davies",
           park: "West",
           type: "Traditional",
		   capacity: 134,
		   dataProj: true,
		   ohp: true,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "B009",
		   building: "Brockington",
           park: "Central",
           type: "Traditional",
		   capacity: 110,
		   dataProj: false,
		   ohp: true,
		   whiteboard: true,
		   chalkboard: false,
		   wheelchair: true},
		   { name: "J002",
		   building: "EHB",
           park: "Central",
           type: "Traditional",
		   capacity: 105,
		   dataProj: true,
		   ohp: true,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "A001",
		   building: "Schofield",
           park: "Central",
           type: "Traditional",
		   capacity: 101,
		   dataProj: true,
		   ohp: true,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "JB021",
		   building: "Sir John Beckwith Centre for Sport",
           park: "East",
           type: "Traditional",
		   capacity: 100,
		   dataProj: true,
		   ohp: true,
		   whiteboard: true,
		   chalkboard: false,
		   wheelchair: true},
		   { name: "XX019",
		   building: "Bridgeman Centre",
           park: "Central",
           type: "Traditional",
		   capacity: 100,
		   dataProj: true,
		   ohp: false,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "S004",
		   building: "S Building",
           park: "West",
           type: "Traditional",
		   capacity: 98,
		   dataProj: true,
		   ohp: true,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "A201",
		   building: "Schofield",
           park: "Central",
           type: "Traditional",
		   capacity: 95,
		   dataProj: true,
		   ohp: false,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "JJ004",
		   building: "Ann Packer",
           park: "East",
           type: "Traditional",
		   capacity: 90,
		   dataProj: false,
		   ohp: false,
		   whiteboard: true,
		   chalkboard: false,
		   wheelchair: true},
		   { name: "W004",
		   building: "Sir David Davies",
           park: "West",
           type: "Traditional",
		   capacity: 84,
		   dataProj: true,
		   ohp: true,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "B111",
		   building: "Brockington",
           park: "Central",
           type: "Traditional",
		   capacity: 80,
		   dataProj: true,
		   ohp: true,
		   whiteboard: true,
		   chalkboard: false,
		   wheelchair: true},
		   { name: "RT005",
		   building: "Sir Frank Gibb",
           park: "West",
           type: "Traditional",
		   capacity: 75,
		   dataProj: false,
		   ohp: true,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "RT011",
		   building: "Sir Frank Gibb",
           park: "West",
           type: "Traditional",
		   capacity: 72,
		   dataProj: false,
		   ohp: false,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "RT023",
		   building: "Sir Frank Gibb",
           park: "West",
           type: "Traditional",
		   capacity: 72,
		   dataProj: false,
		   ohp: false,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "W003",
		   building: "Sir David Davies",
           park: "West",
           type: "Traditional",
		   capacity: 69,
		   dataProj: true,
		   ohp: true,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "ZZ106",
		   building: "Matthew Arnold",
           park: "East",
           type: "Traditional",
		   capacity: 64,
		   dataProj: false,
		   ohp: true,
		   whiteboard: true,
		   chalkboard: true,
		   wheelchair: false},
		   { name: "U011",
		   building: "Brockington Extension",
           park: "Central",
           type: "Traditional",
		   capacity: 60,
		   dataProj: false,
		   ohp: true,
		   whiteboard: true,
		   chalkboard: false,
		   wheelchair: true},
		   { name: "X401",
		   building: "Pilkington Library",
           park: "West",
           type: "Traditional",
		   capacity: 60,
		   dataProj: false,
		   ohp: false,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "S174",
		   building: "S Building",
           park: "West",
           type: "Traditional",
		   capacity: 53,
		   dataProj: false,
		   ohp: true,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "A203",
		   building: "Schofield",
           park: "Central",
           type: "Traditional",
		   capacity: 50,
		   dataProj: true,
		   ohp: true,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "D002",
		   building: "James France",
           park: "Central",
           type: "Traditional",
		   capacity: 50,
		   dataProj: false,
		   ohp: false,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "D102",
		   building: "James France",
           park: "Central",
           type: "Traditional",
		   capacity: 50,
		   dataProj: false,
		   ohp: true,
		   whiteboard: true,
		   chalkboard: true,
		   wheelchair: false},
		   { name: "D109",
		   building: "James France",
           park: "Central",
           type: "Traditional",
		   capacity: 50,
		   dataProj: false,
		   ohp: true,
		   whiteboard: true,
		   chalkboard: true,
		   wheelchair: false},
		   { name: "D201",
		   building: "James France",
           park: "Central",
           type: "Traditional",
		   capacity: 50,
		   dataProj: false,
		   ohp: true,
		   whiteboard: true,
		   chalkboard: true,
		   wheelchair: false},
		   { name: "D202",
		   building: "James France",
           park: "Central",
           type: "Traditional",
		   capacity: 50,
		   dataProj: false,
		   ohp: true,
		   whiteboard: true,
		   chalkboard: true,
		   wheelchair: false},
		   { name: "JJ010",
		   building: "Ann Packer",
           park: "East",
           type: "Traditional",
		   capacity: 50,
		   dataProj: false,
		   ohp: true,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "S173",
		   building: "S Building",
           park: "West",
           type: "Traditional",
		   capacity: 50,
		   dataProj: false,
		   ohp: true,
		   whiteboard: false,
		   chalkboard: true,
		   wheelchair: true},
		   { name: "N004",
		   building: "Haslegrave",
           park: "Central",
           type: "Lab",
		   capacity: 50,
		   dataProj: true,
		   ohp: false,
		   whiteboard: false,
		   chalkboard: false,
		   wheelchair: true},
		   { name: "N006",
		   building: "Haslegrave",
           park: "Central",
           type: "Lab",
		   capacity: 60,
		   dataProj: true,
		   ohp: false,
		   whiteboard: false,
		   chalkboard: false,
		   wheelchair: true},
		   { name: "N005",
		   building: "Haslegrave",
           park: "Central",
           type: "Lab",
		   capacity: 90,
		   dataProj: true,
		   ohp: false,
		   whiteboard: false,
		   chalkboard: false,
		   wheelchair: true},
		   ];

var bookings = [
		 { period: 1,
		   day: 1,
		   room: "RT003" } ,
		 { period: 1,
		   day: 1,
		   room: "Cope" } ,
		 { period: 1,
		   day: 1,
		   room: "J002" } ,
		 { period: 1,
		   day: 1,
		   room: "A001" } ,
		 { period: 1,
		   day: 1,
		   room: "JJ017" } ,
		  { period: 1,
		   day: 1,
		   room: "JB021" } ,
		  { period: 1,
		   day: 1,
		   room: "JJ004" } ,
		 { period: 1,
		   day: 1,
		   room: "ZZ106" } ,
		  { period: 1,
		   day: 1,
		   room: "JJ010" } ,  
		 { period: 1,
		   day: 1,
		   room: "Cope" } ,
		 { period: 1,
		   day: 3,
		   room: "J002" } ,
		 { period: 1,
		   day: 3,
		   room: "A001" } ,
		 { period: 1,
		   day: 3,
		   room: "JJ017" } ,
		  { period: 1,
		   day: 3,
		   room: "JB021" } ,
		  { period: 1,
		   day: 3,
		   room: "JJ004" } ,
		 { period: 1,
		   day: 3,
		   room: "ZZ106" } ,
		 { period: 5,
	 	   day: 5,
		   room: "ZZ106" } ,
		 { period: 5,
	 	   day: 5,
		   room: "D102" } ,
		 { period: 5,
	 	   day: 5,
		   room: "D109" } ,
		 { period: 5,
	 	   day: 5,
		   room: "D201" } ,
		 { period: 5,
	 	   day: 5,
		   room: "D202" } ,
		 { period: 3,
	 	   day: 2,
		   room: "N004" } ,
		 { period: 3,
	 	   day: 2,
		   room: "N005" } ,
		 { period: 3,
	 	   day: 3,
		   room: "JJ017" } ,
		 { period: 4,
	 	   day: 3,
		   room: "JJ017" } ,
		 { period: 6,
	 	   day: 2,
		   room: "JJ017" } ,
		 { period: 1,
	 	   day: 4,
		   room: "JJ017" } ,
		 { period: 3,
	 	   day: 4,
		   room: "JJ017" } ,
		 { period: 9,
	 	   day: 5,
		   room: "JJ017" } ,
		 { period: 3 ,
	 	   day: 1,
		   room: "K103" } ,
		 { period: 4,
	 	   day: 1,
		   room: "K103" } ,
		 { period: 8,
	 	   day: 1,
		   room: "K103" } ,
		 { period: 9,
	 	   day: 1,
		   room: "K103" } ,
		 { period: 7,
	 	   day: 2,
		   room: "K103" } ,
		 { period: 1,
	 	   day: 2,
		   room: "K103" } ,
		 { period: 2,
	 	   day: 3,
		   room: "K103" } ,
		 { period: 3,
	 	   day: 3,
		   room: "K103" } ,
		 { period: 2,
	 	   day: 4,
		   room: "K103" } ,
		 { period: 3,
	 	   day: 4,
		   room: "K103" } ,
		 { period: 1,
	 	   day: 1,
		   room: "S175" } ,
		 { period: 2,
	 	   day: 1,
		   room: "S175" } ,
		 { period: 3,
	 	   day: 1,
		   room: "S175" } ,
		 { period: 4,
	 	   day: 1,
		   room: "S175" } ,
		 { period: 5,
	 	   day: 1,
		   room: "S175" } ,
		 { period: 6,
	 	   day: 1,
		   room: "S175" } ,
		 { period: 7,
	 	   day: 1,
		   room: "S175" } ,
		 { period: 8,
	 	   day: 1,
		   room: "S175" } ,
		 { period: 9,
	 	   day: 1,
		   room: "S175" } ,
		 { period: 5,
	 	   day: 5,
		   room: "S175" },
		 { period: 2,
	 	   day: 1,
		   room: "RT003" } ,
		 { period: 2,
	 	   day: 2,
		   room: "RT003" } ,
		 { period: 2,
	 	   day: 3,
		   room: "RT003" } ,
		 { period: 2,
	 	   day: 4,
		   room: "RT003" } ,
		 { period: 2,
	 	   day: 5,
		   room: "RT003" } ,
		 { period: 5,
	 	   day: 3,
		   room: "RT003" } ,
		 { period: 5,
	 	   day: 4,
		   room: "RT003" } ,
		 { period: 5,
	 	   day: 5,
		   room: "RT003" } ,
		 { period: 4,
	 	   day: 3,
		   room: "RT003" } ,
		 { period: 4,
	 	   day: 2,
		   room: "RT003" },
		   { period: 1,
	 	   day: 2,
		   room: "Cope" } ,
		 { period: 2,
	 	   day: 2,
		   room: "Cope" } ,
		 { period: 3,
	 	   day: 4,
		   room: "Cope" } ,
		 { period: 4,
	 	   day: 4,
		   room: "Cope" } ,
		 { period: 5,
	 	   day: 4,
		   room: "Cope" } ,
		 { period: 6,
	 	   day: 4,
		   room: "RT008" } ,
		 { period: 7,
	 	   day: 5,
		   room: "RT008" } ,
		 { period: 8,
	 	   day: 5,
		   room: "RT008" } ,
		 { period: 1,
	 	   day: 5,
		   room: "W001" } ,
		 { period: 9,
	 	   day: 1,
		   room: "W001" }
		   ];
